### ISSUE TITLE
WProofreader Integration with ckeditor5

### ISSUE THREAD

**Issue by dil-bparihar** [Mati365/ckeditor5-rails#12]
# ✨ Feature Request
WProofreader Integration with ckeditor5
### 🎯 Feature Description
How can we add this as plugin in ckeditor5.
https://ckeditor.com/docs/ckeditor5/latest/features/spelling-and-grammar-checking.html

A clear and concise description of what feature you would like to see implemented.

### 🤔 Problem Statement

A clear and concise description of what problem this feature would solve. Example: "I'm always frustrated when..."

### 📋 Implementation Details

Any technical details or considerations that might be helpful.

**Comment by dil-bparihar** [comment]
@Mati365  I need to integrate this https://ckeditor.com/docs/ckeditor5/latest/features/spelling-and-grammar-checking.html
With our gem for ckeditor5. Do we have methods and configuration to setup it currently.

**Comment by Mati365** [comment]
@dil-bparihar It should be possible to do that manually at this moment. Afair, all you have to do is:

1. Add CSS files from their CDN to page (https://cdn.jsdelivr.net/npm/@webspellchecker/wproofreader-ckeditor5@3.1.2/dist/browser/index.css)
2. Add importmap script somewhere in the header (https://cdn.jsdelivr.net/npm/@webspellchecker/wproofreader-ckeditor5@3.1.2/+esm)
3. Add plugin somewhere in preset `plugin :WProofReader, import_name: <import name from your import map>`
4. Configure your reader using `configure` helper of preset.

Looks kinda complicated. I'll consider adding some API to load such external plugins a little bit more user-friendly.

**Comment by dil-prmishra** [comment]
Hi @Mati365 , is it possible to integrate CKBox for file management with this gem?

**Comment by Mati365** [comment]
Yep, consider using `ckbox` helper: https://github.com/Mati365/ckeditor5-rails?tab=readme-ov-file#ckbox-method

**Comment by dil-bparihar** [comment]
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/9fd55005-311f-4cb6-981d-043cce6e3e33">
@Mati365

**Comment by Mati365** [comment]
@dil-bparihar Kinda weird, maybe bug in CKEditor. Can you show the configuration you used to place it in your app?

**Comment by dil-bparihar** [comment]
I just pasted the cdn in layout no other config. Just when refreshed the page editor was gone with this error i posted.

**Comment by Mati365** [comment]
ok, I'll check that.

**Comment by dil-bparihar** [comment]
plugin :WProofReader, import_name: <import name from your import map>

how it will be use as ?

**Comment by dil-bparihar** [comment]
i need to put this as:

plugin :YourPlugin, import_name: 'https://cdn.jsdelivr.net/npm/@webspellchecker/wproofreader-ckeditor5@3.1.2/dist/browser/index.js'

**Comment by Mati365** [comment]
nope, importmap should contain alias to your remote import. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap. Depending how it looks like in your page, it should look like this:

```plugin :WProofReader, import_name: 'wproofreader'``` where:

```
<script type="importmap">
  {
    "imports": {
      "wproofreader": "https://cdn.jsdelivr.net/npm/@webspellchecker/wproofreader-ckeditor5@3.1.2/dist/browser/index.js"
    }
  }
</script>
```

**Comment by Mati365** [comment]
@dil-bparihar You need to add CSS files of wproofreader somewhere in your header, and then append `importmap` script after ckeditor5 assets. When you add `plugin :WProofReader, import_name: 'wproofreader'`, the integration will try to import such package from that URL as the `WProofReader` plugin.

**Comment by dil-bparihar** [comment]
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/e547502b-a281-4cb9-ac88-2c7f0336b0e4">

@Mati365  It feels very hard to configure. Can you try at your end.

**Comment by Mati365** [comment]
Kinda weird, I'll extend integration later this day.

**Comment by dil-bparihar** [comment]
Thanks @Mati365

**Comment by Mati365** [comment]
@dil-bparihar I added helper to autoload `wproofreader`. Please take a look: https://github.com/Mati365/ckeditor5-rails?tab=readme-ov-file#wproofreaderversion-nil-cdn-nil-config-method

```rb
# config/initializers/ckeditor5.rb

CKEditor5::Rails.configure do
  # ... other configuration

  wproofreader serviceId: 'your-service-ID',
               srcUrl: 'https://svc.webspellchecker.net/spellcheck31/wscbundle/wscbundle.js'
end
```

**Comment by dil-bparihar** [comment]
@Mati365  Is it possible if user has not specified language for wproofreader then it should pick default language as I18n.locale

**Comment by dil-prmishra** [comment]
@Mati365 , How to add ckbox-plugin-missing-token-url to utilize ckbox file manager in this gem?

**Comment by Mati365** [comment]
@dil-prmishra According to the docs of the CKBox plugin: https://ckeditor.com/docs/ckeditor5/latest/api/module_ckbox_ckboxconfig-CKBoxConfig.html, you need to use `configure` initializer helper to pass token url

**Comment by Mati365** [comment]
@dil-bparihar I updated behavior of the gem. If no language is specified, then it'll try to use the language from the editor (which is specified using `language:`). Change: https://github.com/Mati365/ckeditor5-rails/commit/934b0968c5e9ec3cfa3f51f72a14cae963fa7fd7

Please upgrade to `1.18.3`. Thanks!

**Comment by dil-bparihar** [comment]
Thanks @Mati365
