### ISSUE TITLE
Ckeditor Assets is not loading for js request call.

### ISSUE THREAD

**Issue by dil-bparihar** [Mati365/ckeditor5-rails#13]
# 🐛 Bug Report

### 🔍 Bug Description
The ckeditor5 gem works as expected for HTTP requests that render full-page responses. However, it fails to reinitialize when the page is updated via JavaScript (e.g., js format requests or Turbo Streams). As a result, CKEditor does not function on dynamically rendered content.

### 📝 Steps to Reproduce

1. Install and configure the ckeditor5 gem as per the documentation.
2. Add a form or content block in your view that uses CKEditor.
3. Perform an action that updates part of the page via a JavaScript (js) request (e.g., a form submission using remote: true or Turbo Streams).
4. Observe that CKEditor fails to initialize on the dynamically rendered content.

### ✅ Expected Behavior
CKEditor should reinitialize and work properly on content that is dynamically added to the DOM via JavaScript requests.

### ❌ Actual Behavior
CKEditor does not reinitialize or function on dynamically rendered content added via JavaScript requests.
A clear and concise description of what actually happened.

### 📋 Additional Context

- Add any other context about the problem here
- Include relevant logs if available
- List related issues/PRs

**Comment by Mati365** [comment]
Don't get it. Please reformat issue with code sample

**Comment by dil-bparihar** [comment]
@Mati365  i have updated the my comment

**Comment by Mati365** [comment]
@dil-bparihar Ok, got it. So you transfer ckeditor web component and it's not initialized after attaching to site. It can be problematic, as editor require some resources to be added to the head. 

I'll add some additional configuration option that checks presence of importmap, and restores it if it's not present. Will be done next week

**Comment by dil-bparihar** [comment]
Yes @Mati365  So for `Processing by SettingsController#general as JS` request to the controller which renders the application.js.erb  it is having a problem.

**Comment by Mati365** [comment]
@dil-bparihar `ckeditor5_assets` is present somewhere in the head? Is it added using turbolinks?

**Comment by dil-bparihar** [comment]
Using yield :head in layout and calling method below in pages or partial for the current controller for http request works as expected
```
- content_for :head do
  = ckeditor5_assets preset: :welcome
- breadcrumb :welcome_edit
```

but for `Processing by SettingsController#general as JS` js requests where it is rendering 
`Rendering layout layouts/application.js.erb `

It is having the issues.

@Mati365

**Comment by Mati365** [comment]
Ok, I'll check that. Pretty weird, as it's using web components.

**Comment by Mati365** [comment]
@dil-bparihar I had to port integration to Rails 8. I'll check it later this day.

**Comment by Mati365** [comment]
@dil-bparihar I added AJAX Form demo: https://github.com/Mati365/ckeditor5-rails/blob/main/sandbox/app/views/demos/form_ajax.slim. It looks like it works without any modification of the integration.

https://github.com/user-attachments/assets/24082bb8-7885-4fc4-a9d0-d2cc25520753

**Comment by Mati365** [comment]
@dil-bparihar Consider skipping using `content_for :head` in this case, it should work. It'll duplicate some styling and scripts, but it should work.

**Comment by dil-bparihar** [comment]
![image](https://github.com/user-attachments/assets/b505796b-89c0-4f1f-937a-95997682976a)
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/75dcdefd-7046-4f19-8e57-437975352e1d">

@Mati365  When loading directly getting this error in the screenshot.

**Comment by dil-bparihar** [comment]
And if i load directly ckeditor5_assets into application.html.haml then i will not be able to use specific preset for a specific editor. @Mati365

**Comment by dil-bparihar** [comment]
Means we will load files at once to the layout @Mati365

**Comment by Mati365** [comment]
@dil-bparihar Nope, import maps just tell the browser mapping between names of the imports and the URLs.

**Comment by dil-bparihar** [comment]
Most of my editors are in the pages which rendering with js call only. And i am not getting any proper solution. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar I'm preparing `lazy` flag addition to `ckeditor5_assets`, which will tell the integration to skip loading editor until it first appears on the page. Currently, you have to attach editor at the first request.

**Comment by dil-bparihar** [comment]
@Mati365 
<img width="233" alt="image" src="https://github.com/user-attachments/assets/8a88a27b-0cdd-436b-8fbd-04bdaab0bd3d">
<img width="933" alt="image" src="https://github.com/user-attachments/assets/62bf7800-86b0-40d6-ab8a-a1e060712b35">


Button icon is not visible. Using like in the screenshot in custom plugin.

**Comment by dil-bparihar** [comment]
@Mati365 How can we achieve this kind of grouping with dropdown. For example i want to add a button for my custom plugin to imageInsert toolbar dropdown.

<img width="824" alt="image" src="https://github.com/user-attachments/assets/2c774b8f-68ae-4480-aec2-4ceebd6a6d1b">

**Comment by Mati365** [comment]
@dil-bparihar I deployed `1.21.0` version with improved turbolinks support.  Please check these demos files:

https://github.com/Mati365/ckeditor5-rails/blob/main/sandbox/app/views/demos/form_ajax.slim
https://github.com/Mati365/ckeditor5-rails/blob/main/sandbox/app/views/demos/_form_ajax_response.slim

Integration should be smart enough to load dependencies on it's own. The `= ckeditor5_lazy_javascript_tags` injects importmap and small webcomponent script, no ckeditor 5 files will be loaded until you load it using turbolinks. 

> How can we achieve this kind of grouping with dropdown. For example i want to add a button for my custom plugin to imageInsert toolbar dropdown.

It's not supported at this moment. You have to use `configure` helper in initializer.

**Comment by dil-bparihar** [comment]
How can we import libraries like 
`import ImageInsertUI from '@ckeditor/ckeditor5-image/src/imageinsert/ui/imageinsertui';` in our custom plugin. I tried doing it. Like `import ImageInsertUI from 'ckeditor5';` Button getting error as undefined method.

@Mati365

**Comment by Mati365** [comment]
@dil-bparihar it's impossible in newer versions of the CKEditor 5, as they have single `dist/index.js` file. Try:

```tsx
import { ImageInsertUI } from 'ckeditor5';
```

**Comment by Mati365** [comment]
> How can we achieve this kind of grouping with dropdown. For example i want to add a button for my custom plugin to imageInsert toolbar dropdown.

@dil-bparihar I added support for grouping the toolbars using `group` toolbar builder method. Example:

```rb
# config/initializers/ckeditor5.rb

CKEditor5::Rails.configure do
  # ... other configuration

  toolbar do
    group :text_formatting, label: 'Text Formatting', icon: 'threeVerticalDots' do
      append :bold, :italic, :underline, :strikethrough, separator,
             :subscript, :superscript, :removeFormat
    end
  end
end
```

Please upgrade to `1.22.0`. I'm closing this issue.
