### ISSUE TITLE
What is the best way to use custom plugin ?

### ISSUE THREAD

**Issue by dil-bparihar** [Mati365/ckeditor5-rails#17]
# 🐛 Bug Report
What is the best way to use custom plugin ?
### 🔍 Bug Description
@Mati365  I have created a plugin which will open up my custom file manager to select image and add it in the editor. What is the best way to create custom plugin and use it. Currently i am using it as an inline plugin. But you have also mentioned readme that:

⚠️ Warning: Use with caution as this is an inline definition of the plugin code, and it can potentially cause XSS vulnerabilities. Only use this method with static, trusted JavaScript code.

### ❌ Actual Behavior

A clear and concise description of what actually happened.

### 📸 Screenshots
![image](https://github.com/user-attachments/assets/47b5e05e-5c16-494e-bbb9-b2bcf8b55916)

### 📋 Additional Context

- Add any other context about the problem here
- Include relevant logs if available
- List related issues/PRs

**Comment by dil-bparihar** [comment]
My application is on rails 6.1. What is your suggestion to use from above 3 ways. @Mati365

**Comment by dil-bparihar** [comment]
Also i am trying to use 

import { Notification } from 'ckeditor5';
const notification = editor.plugins.get(Notification);
notification.showInfo('Hello, world!');


but not getting the notification message in the editor UI. Also not getting any error. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-ui/src/notification/notification.ts#L45 , probably alert is being blocked in your browser. Consider adding custom listener, with high priority and cancel the default one. You have to use custom implementation of alerts probably.

**Comment by Mati365** [comment]
I disallowed definition of inline plugins in the controller and added signing of their content. It should be much harder to write unsafe code right now.

**Comment by dil-bparihar** [comment]
@Mati365  It is breaking due to our strict Content-Security-Policy. Inline plugin causing issues.

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/f60c1095-b84e-4454-a991-156d5201e3bd" />

**Comment by Mati365** [comment]
Please send me whole CSP

**Comment by dil-bparihar** [comment]
@Mati365 "default-src https: 'unsafe-eval' 'unsafe-inline'; img-src https: data:; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com data:; worker-src blob:; object-src 'none';"

**Comment by Mati365** [comment]
Most likely nonce needs to be added. I'll check that.

**Comment by dil-bparihar** [comment]
Is there any alternate i can use for now to resolve it. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar Consider upgrade to `1.23.5`. I messed something with `nonce` support. It should work for this CSP configuration: https://github.com/Mati365/ckeditor5-rails/blob/main/sandbox/config/initializers/content_security_policy.rb

**Comment by dil-bparihar** [comment]
I have upgraded the gem to 1.23.5. But still the same error i am facing. @Mati365 
<img width="1449" alt="image" src="https://github.com/user-attachments/assets/932ffff2-90c9-4ff5-8f4c-b2478d00063c" />

**Comment by Mati365** [comment]
Adjust your CSP configuration to that one presented in the file above. Check response of the https://ckeditor5-rails.mati365.ovh/

**Comment by dil-bparihar** [comment]
config.action_dispatch.default_headers.merge!(
    "Content-Security-Policy" => "default-src https:; script-src 'strict-dynamic' https: 'unsafe-eval' 'nonce-#{SecureRandom.base64(16)}'; img-src https: data:; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com data:; worker-src blob:; object-src 'none';"
  )
  
  now using this but it is breaking everything now.
  
  
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/882cb444-3bfc-46a2-8881-38126a4dcd04" />

**Comment by Mati365** [comment]
@dil-bparihar In such case, you need to add `nonce` attributes to your other scripts on the page, as it's said in the error message. If it's impossible, then you need to use `importmap-rails` gem and attach your plugin manually.  You can also try to use window object to pass plugin to the editor. In other words:

```erb
= javascript_include_tag "path-to-your-plugin-in-assets.js", type: "module" 
````

where the `js` file is something like that:

```js
import { Plugin } from 'ckeditor5';

window.YourPlugin = class YourPlugin extends Plugin {
   ...
};
```

and then somewhere in initializer:

```rb
plugin :YourPlugin, window_name: :YourPlugin
```

I'd recommend using `nonce` or `importmap-rails`. You can check demo: https://github.com/Mati365/ckeditor5-rails/tree/main/sandbox

**Comment by dil-bparihar** [comment]
using global object is safe ? using import-rails or nonce its not possible for now. 

Can we have any other solution which could work also safe ? @Mati365

**Comment by Mati365** [comment]
@dil-bparihar That's the problem with the ESM ecosystem and older assets pipeline that was designed for CJS. There is no such many ways to fix that issue without using importmaps or adjusting CSP. However... what I'm thinking about is adding queue, that will allow you to intercept configuration of the editor just before mounting in to the DOM. Something like that:

```tsx
window.addEventListener( 'ckeditor5:before-mount', () => {
  const { Plugin } = window.CKEDITOR;

   window.YourPlugin = class YourPlugin extends Plugin { ... };
});
```

and then in your initializer:

```rb
plugin :YourPlugin, window_name: 'YourPlugin'
```

**Comment by dil-bparihar** [comment]
Yes we can try doing it. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar ok, I'll release gem later this day with such broadcast. Maybe I'll add only additional flag to `inline_plugin`, such like: `cjs: true`, to keep it consistent. At this moment, don't change your code.

**Comment by dil-bparihar** [comment]
For now i am using global object only.

**Comment by Mati365** [comment]
@dil-bparihar I updated docs, it's now possible to use `inline_plugin` without any additional flag in your setup. I had to update format of inline plugins:

```ts
  inline_plugin :MyCustomPlugin,  <<~JS
      const { Plugin } = await import( 'ckeditor5' );
  
      return class MyCustomPlugin extends Plugin {
        // ...
      }
  JS
```
so `const { .. } = await import` must be used instead of `import`

**Comment by dil-bparihar** [comment]
how i can give the path of my plugin code js file in this ? @Mati365

**Comment by Mati365** [comment]
@dil-bparihar I'm not sure if I understand it correctly. Generally speaking, that one: 

```rb
inline_plugin :MyCustomPlugin, File.read(
    Rails.root.join('app/javascript/custom_plugins/highlight.js')
  )
```

should be working correctly

**Comment by dil-bparihar** [comment]
Sure, I mean to say the way i was using it earlier but having issues with my csp rules. And it was breaking still after adding your suggested code. So now if i follow this:

```
inline_plugin :MyCustomPlugin, File.read(
    Rails.root.join('app/javascript/custom_plugins/highlight.js')
  )
```
And my code will be like this only:

```
const { Plugin } = await import( 'ckeditor5' );

    return class extends Plugin {
      static get pluginName() {
        return 'MyCustomPlugin';
      }

      init() {
        const config = this.editor.config.get('myCustomPlugin') || {};

        // ... Your plugin code
      }
    }
```

It will work without any issues with my current csp rules for the application. @Mati365

**Comment by Mati365** [comment]
Yep, @dil-bparihar. I changed the mechanism used to load inline-plugins, and they are added to the `head` during server side rendering, instead of the evaluation of on the client side. I hope there will be no CSP errors anymore.

**Comment by dil-bparihar** [comment]
Just one thing when following new format:

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/61fea9ea-58ed-44f8-8ec3-f5533abce8cc" />

<img width="703" alt="image" src="https://github.com/user-attachments/assets/ad17d8a1-1ecc-4d00-84ac-0847792fe996" />

**Comment by dil-bparihar** [comment]
Yes, using this only:

inline_plugin :MyCustomPlugin, File.read(
    Rails.root.join('app/javascript/custom_plugins/highlight.js')
  )

**Comment by Mati365** [comment]
@dil-bparihar but it's loading `imageupload` file, not the `highlight`, so something is wrong in your plugin attachement. Check if `file manager plugin` is inline plugin

**Comment by dil-bparihar** [comment]
@Mati365  My code is:

```
inline_plugin :FileManagerPlugin, File.read(
  Rails.root.join('app/javascript/ckeditor_plugins/imageupload.js')
)
```

```
const { Plugin , icons, ButtonView } = await import( 'ckeditor5' );
const { ImageInsertUI } = await import( 'ckeditor5' );

return class extends Plugin {
  static get pluginName() {
    return 'FileManagerPlugin';
  }

  init() {
    const editor = this.editor;
  }
  
}
```

**Comment by Mati365** [comment]
@dil-bparihar Yep, but take a look at the screen. It's executing code from the `imageupload-<hash>.js`, it means that your original file is attached somewhere on the page.

**Comment by dil-bparihar** [comment]
Ohhh yes. Thanks a lot. I forgot to remove javascript_pack_tag from the layout for the file last added for window object. @Mati365

**Comment by Mati365** [comment]
Good, so CSP no longer crashes @dil-bparihar ?

**Comment by dil-bparihar** [comment]
I can tell you that in another half an hour after deploying the code and testing @Mati365

**Comment by dil-bparihar** [comment]
@Mati365  On my local it is working fine. But when i deployed the code to production. Site started giving 504 timeout. I am not able to figure out why ?

but when i run assets precompile its throwing error something like this:

SyntaxError: /home/app/be/app/javascript/packs/ckeditor_plugins/imageupload.js: 'return' outside of function. (4:0)

  2 | const { ImageInsertUI } = await import( 'ckeditor5' );
  3 |
> 4 | return class extends Plugin {
    | ^
  5 |   static get pluginName() {
  6 |     return 'FileManagerPlugin';
  7 |   }

**Comment by Mati365** [comment]
@dil-bparihar it's trying to precompile that should be ignored, ignore whole `ckeditor_plugins` in the assets pipeline. Regardless, 504 - dunno. You need to check logs.

**Comment by Mati365** [comment]
@dil-bparihar I forgot to document one thing, when CKEditor is being loaded on the page and it lookups for plugin defined as window variable (`plugin :Plugin, window_name: 'YourWindowPluginEntry'`), then it should fire event on the `window`:

```js
        window.addEventListener('ckeditor:request-cjs-plugin:YourWindowPluginEntry', () => {
          window.YourWindowPluginEntry = new Promise((resolve) => {
               const { Plugin } = await import( 'ckeditor5' );      
 
              class YourPluginDefinition extends Plugin { .... };

              resolve(YourPluginDefinition);
          });
        }, { once: true });
```

it may be helpful when used together with webpacker

**Comment by dil-bparihar** [comment]
It is strange if i follow the latest format. it is throwing network timeout:

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/945f06a9-a90c-4a99-8ce6-0d1cbbd67cc1" />

And if i use global object it is working fine. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar Without logs, nothing I can do. Consider disabling `automatic_upgrades enabled: false`.

**Comment by dil-bparihar** [comment]
Is it possible if we can use custom plugin js via npm for adding plugin. @Mati365

**Comment by Mati365** [comment]
@dil-bparihar I'm not sure how your application handles JavaScript files. If it's the classical approach, where your assets are placed somewhere in the `<head>` then you can choose one approach from below.

### Import npm package from local `node_modules/`
 
```ts
import { YourPlugin } from 'your-plugin-path';

window.YourPlugin = YourPlugin;
```

and later in the initializer:

```rb
plugin :YourPlugin, window_name: 'YourPlugin'
```

... then the `YourPlugin` will be picked from the Window. I really depend on the format of package that you want to import. If it's ESM package, then it's the only way (except using importmaps). If it's UMD package then it already exports global variable and there is no need to re-export it on the Window.

### Import package from the CDN

#### Using extending class approach

Take a look at WProofreader plugin: 
https://github.com/Mati365/ckeditor5-rails?tab=readme-ov-file#external_pluginname-script-import_as-nil-window_name-nil-stylesheets--method, and then append it to your initializer using these methods: 
https://github.com/Mati365/ckeditor5-rails/blob/main/lib/ckeditor5/rails/presets/preset_builder.rb#L359C1-L365C10

#### Using `external_plugin` initializer helper

https://github.com/Mati365/ckeditor5-rails/tree/main?tab=readme-ov-file#external_pluginname-script-import_as-nil-window_name-nil-stylesheets--method

**Comment by dil-bparihar** [comment]
@Mati365  We have shakapacker. May be i will try to follow below one suggested by you:

`plugin :Plugin, window_name: 'YourWindowPluginEntry')`


```javascript
window.addEventListener('ckeditor:request-cjs-plugin:YourWindowPluginEntry', () => {
          window.YourWindowPluginEntry = new Promise((resolve) => {
               const { Plugin } = await import( 'ckeditor5' );      
 
              class YourPluginDefinition extends Plugin { .... };

              resolve(YourPluginDefinition);
          });
        }, { once: true });
```
