### ISSUE TITLE
undefined local variable or method 'ckeditor5_assets'

### ISSUE THREAD

**Issue by dil-bparihar** [Mati365/ckeditor5-rails#2]
I am following the installation steps for the gem as outlined, but I'm encountering an error stating that ckeditor5_assets is an undefined local variable or method. Additionally, when I create the ckeditor5.rb file in the initializer, I receive an error at /config/initializers/ckeditor5.rb:1:in <top (required)>': uninitialized constant CKEditor5 (NameError) 2024-11-05 18:11:13. Did you mean? Ckeditor. It appears that the gem is not loading properly. @Mati365 

Can you please help.

Rails version: 6.1.7.6
Ruby: 3

**Comment by Mati365** [comment]
@dil-bparihar Try updating gem to `1.5.0`
