### ISSUE TITLE
CKEditor5 Field Not Saving Properly

### ISSUE THREAD

**Issue by dil-bparihar** [Mati365/ckeditor5-rails#3]
Description
When using the following code:

erb:

`<%= f.ckeditor5 :content, required: true, style: 'width: 700px', initial_data: 'Hello World!' %>`

The content is not being saved correctly.

Cause
The issue seems to be in hooks/form.rb, specifically within the ckeditor5 method in the FormBuilderExtension module.

Suggested Fix
Updating the ckeditor5 method as shown below resolves the issue:

```
module CKEditor5
  module Rails
    module Hooks
      module Form
        module FormBuilderExtension
          def ckeditor5(method, options = {})
            value = if object.respond_to?(method)
                      object.send(method)
                    else
                      options[:initial_data]
                    end

            html_options = options.merge(
              name: "#{object_name}[#{method]}",  # Ensures it submits as "client[content]"
              required: options.delete(:required),
              initial_data: value
            )

            @template.ckeditor5_editor(**html_options)
          end
        end
      end
    end
  end
end
```
This adjustment ensures that the input is properly named (e.g., client[content]), allowing it to be saved correctly.

Request
Please consider updating the gem to incorporate this fix.

Thank you!

**Comment by Mati365** [comment]
Thanks! I'll check that

**Comment by Mati365** [comment]
@dil-bparihar I updated gem, please check version `1.5.4`.

**Comment by dil-bparihar** [comment]
Thanks @Mati365  Its working.
