### ISSUE TITLE
Setting the height and width using the style attribute is not increasing the size of the text box.

### ISSUE THREAD

**Issue by dil-bparihar** [Mati365/ckeditor5-rails#5]
# 🐛 Bug Report
Setting the height and width using the style attribute is not increasing the size of the text box.
### ✅ Expected Behavior
The CKEditor5 text box should adjust its height and width according to the values specified in the style attribute. For example, if style="height: 400px; width: 600px;" is applied, the text box should appear with a height of 400 pixels and a width of 600 pixels.

### ❌ Actual Behavior
The CKEditor5 text box does not change its size according to the specified style attributes. Despite setting height and width using inline styles, the text box remains at its default size and does not expand to the specified dimensions.
A clear and concise description of what actually happened.

### 📸 Screenshots
<img width="561" alt="image" src="https://github.com/user-attachments/assets/1aac04f9-4710-4181-b95b-b5607ff317e6">

### 📋 Additional Context

`= ckeditor5_editor initial_data: @body, name: 'email[body]',style: 'height: 300px;'`

- Add any other context about the problem here
- Include relevant logs if available
- List related issues/PRs

**Comment by Mati365** [comment]
@dil-bparihar It's not an issue in the integration itself, as it's how CKEditor 5 supposed to work. Afair, you have to set CSS style directly on editable, like this:

```css
.ck-editor__editable { min-height: 150px; }
```

to make it work.

**Comment by dil-bparihar** [comment]
Trying with this its not working for me @Mati365

**Comment by dil-bparihar** [comment]
Is it possible to configure CSS properties like height or width for the .ck-editor__editable class in the CKEditor configuration (e.g., using a configuration like ckeditor: { height: "400px" }), without having to write inline CSS for each individual editor?

@Mati365

**Comment by Mati365** [comment]
@dil-bparihar Nope, you can use `css` class or even `id` and then style it using `.ck-editor__editable` selector. I'll try to extend the API a bit to use a custom plugin to archive this.

**Comment by Mati365** [comment]
@dil-bparihar I introduced `editable_height` attribute to the editor, it's now possible: https://github.com/Mati365/ckeditor5-rails/commit/1caeec9e00be16b6f6031f36b14764e7ce4a223f

**Comment by dil-bparihar** [comment]
Thanks @Mati365  Its working and helps a lot.
