### ISSUE TITLE
 Request to Add Image Upload Feature to CKEditor5

### ISSUE THREAD

**Issue by dil-prmishra** [Mati365/ckeditor5-rails#6]
Hi,
I wanted to inquire if there are any plans to implement an image upload feature for CKEditor5. As image upload is a critical functionality for many use cases, including ours, it would be a valuable addition to the editor.

Could you please let us know if this feature is on the roadmap, or if there are any workarounds or extensions currently available to enable image uploading?

Thank you for your time and consideration. Looking forward to your response!

**Comment by Mati365** [comment]
@dil-prmishra Hi! I plan to do this, but I do not know the exact date when it'll be implemented. However, there is a workaround. 

At this moment, I added `base64` uploader as plugin in `default` configuration preset of the editor. Take a look at this file:
https://github.com/Mati365/ckeditor5-rails/blob/main/lib/ckeditor5/rails/presets/manager.rb#L52

If you want to add your custom uploader:

1. Override `:default` preset with new `plugins` list that excludes `Base64UploadAdapter`. There is override syntax: https://github.com/Mati365/ckeditor5-rails?tab=readme-ov-file#presets-
2. Create `inline_plugin` that requires `FileRepository` and defines `createUploadAdapter` function on it. It's specified here: https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/upload-adapter.html

**Comment by dil-bparihar** [comment]
@Mati365 how we can use `previewsInData` for mediaEmbed plugin.

**Comment by dil-bparihar** [comment]
Hi @Mati365  can you help us. How to use ckbox. When using this `ckbox '2.5.4', theme: :lark` .
getting below error:
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/e0d08845-40e0-476f-b923-ba88764aef35">

**Comment by Mati365** [comment]
Weird, I'll check that. Try passing `theme: 'lark'`

**Comment by dil-bparihar** [comment]
Tried

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/9e272b30-dbc2-4343-8152-360fb57caf24">

**Comment by Mati365** [comment]
@dil-bparihar Even weirder, I'm checking that.

**Comment by Mati365** [comment]
@dil-bparihar Please upgrade to `1.11.0`. I fixed wrong `theme` parsing, and crashes.

**Comment by Mati365** [comment]
@dil-bparihar Yep

**Comment by dil-bparihar** [comment]
I have updated my last comments @Mati365  can you check. What all config is required.

**Comment by Mati365** [comment]
@dil-bparihar It looks like wrong version of CKBox is passed. Please use latest one - `2.6.0`

**Comment by dil-bparihar** [comment]
Hi @Mati365  By when we can expect to have the image upload and attachment upload feature in the gem. As it is very important feature used by many people. We are also migrating from ckeditor gem to this gem. It would be very helpful for us also.

**Comment by Mati365** [comment]
By the end of the week, most likely. Do you think that the most simple adapter, that only uploads files to backend and expects a URL to asset in the response, will be enough for you?

**Comment by dil-bparihar** [comment]
We were expecting the same functionality for asset upload just like were having in ckeditor4 gem using carrierwave. @Mati365

**Comment by Mati365** [comment]
I'll check what I can do, at this moment you can just grep all base64 images from uploaded HTML, and upload it after sending to the backend. At this moment, I plan to add it in two steps:

1. Add the simplest adapter, that one where we specify `upload_url` and the result is the link to the CDN (this will be done this week). 
2. Add the more advanced adapter with carrierwave(this will be done probably next month).

At this moment, you can write your own plugin using inline_plugin, exactly like it's specified in CKEditor 5 docs.

**Comment by Mati365** [comment]
@dil-bparihar I added https://github.com/Mati365/ckeditor5-rails?tab=readme-ov-file#simple_upload_adapterurl-method config helper for simple upload configuration. Please take a look.

**Comment by Mati365** [comment]
@dil-bparihar Closing for now, please reopen if uploading not work.
